export const ADD_TO_CART='ADD TO CART';
export const REMOVE_FROM_CART='REMOVE FROM CART';
export const EMPTY_CART='EMPTY CART';
export const PROLIST_SELECTED='PROLIST_SELECTED';
export const JSON_DATA='JSON_DATA';